// Name: SAPCube
// Purpose: Explore data for SAP tenant
// Author: mikebreen
// Change Log: 2025-11-19

//[PIN] REFERENCE "/shares/IDEAs.Prod.Data/Common/Parquet/Microsoft.Cosmos.Parquet.dll";
//[PIN] REFERENCE "/shares/IDEAs.Prod.Data/Build/Parquet/Microsoft.Cosmos.Parquet.dll";
//[PIN] REFERENCE "/shares/IDEAs.Prod.Data/Common/OutputFormatters/Microsoft.Cosmos.Parquet.dll";

//[PIN] REFERENCE "/shares/IDEAs.Prod.Data/Common/PrivacyAnnotation/Microsoft.PrivacyServices.PrivacyAnnotation.dll";
//[PIN] REFERENCE "/shares/IDEAs.Prod.Data/Common/PrivacyAnnotation/Microsoft.DataMap.CodeAnnotation.Cosmos.dll";
//USING Microsoft.DataMap.CodeAnnotation.Cosmos;
//USING Privacy;
 
//[PIN]REFERENCE "/shares/IDEAs.Prod.Data/Build/DataFactory/DBGrowth/Resources/Microsoft.Datacenter.Datamining.Cosmos.dll";

// parameters

#DECLARE startDateStr string = "2025-05-01";
#DECLARE endDateStr   string = "2025-11-30";

// ---------------------------
//#DECLARE iStream string = "/shares/IDEAs.Prod.Data/Publish.Usage.User.Commercial.IKS.Prod.Cubes.CopilotActivityUser/Streams/v1/";
#DECLARE iStream string = "/shares/IDEAs.Prod.Data/Publish/Usage/User/Commercial/IKS/Prod/Cubes/CopilotActivityUser/Streams/v1/";
// get the data 
cube = SSTREAM SPARSE STREAMSET @iStream
      PATTERN @"%Y/%m/CopilotUserActivity_cubeDaily_dataset_%Y_%m_%d.ss"
      //      2025/07/CopilotUserActivity_cubeDaily_dataset_2025_07_31.ss"
      RANGE __date = [@startDateStr, @endDateStr];


// ---------------------------
// Output
// ---------------------------


#DECLARE oStreamt string = @"/local/users/mikebreen/" +
                            "SAPActiveUsers_2025.tsv" ;


#DECLARE oStreamp string = @"/shares/IDEAs.Prod.Data/Users.General/mikebreen/SAPActiveUsers_2025.parquet";


// ---------------------------

raw =
    SELECT
        ContentDate,
        Id,
        OMSTenantId,
        UserObjectId,
        EnabledM365CopilotInTeams,
        EnabledM365CopilotInProductivityApps,
        EnabledBusinessChat,
        EnabledIntelligentSearch,
        EnabledPowerPlatformConnectorPlugins,
        EnabledGraphConnectorsCopilot,
        IsActiveInTeams,
        IsActiveInWord,
        IsActiveInPowerPoint,
        IsActiveInExcel,
        IsActiveInOutlook,
        IsActiveInOneNote,
        IsActiveInLoop,
        IsActiveInM365Chat,
        IsActiveInBusinessChatWeb,
        SummarizeTeamsMeetingEventsCount, //
        SummarizeTeamsChatEventsCount,
        SummarizeEmailThreadEventsCount,
        SummarizeDocumentEventsCount,
        SummarizePresentationEventsCount,
        GenerateEmailDraftEventsCount,
        DraftDocumentEventsCount,
        ModifyDocumentEventsCount,
        CreatePresentationEventsCount,
        MeetingsSummarizedCount,
        MeetingMinutesSummarizedCount,
        TeamsThreadsSummarizedCount,
        TeamsComposeActionCount,
        EmailCoachingActionCount,
        EmailsSentWithCopilotDraftCount,
        M365ChatPromptsSubmittedCount,
        ExcelAnalyzeActionCount,
        ExcelCalculateColumnsActionCount,
        ExcelCommandActionCount,
        TeamsCopilotM365ChatPromptsCount,
        OutlookCopilotM365ChatPromptsCount,
        TeamsIntelligentRecapActionCount,
        WordVisualizeAsTableActionCount,
        WordChatActionCount,
        PowerPointAddContentActionCount,
        PowerPointOrganizePresentationActionCount,
        PowerPointChatActionCount,
        ExcelChatActionCount,
        AllAppsCopilotActionCount,  //AllAppsCopilot
        IsReturningInLast7Days,
        IsReturningInLast28Days,
        BusinessChatWebPromptsCount,
        MeetingMinutesSummarizedOrRecappedWithCopilot,
        MeetingsSummarizedOrRecappedWithCopilot,
        MeetingMinutesRecappedWithCopilot,
        MeetingsRecappedWithCopilot,
        IsReturningUserInCopilotChatUnlicensed,
        CopilotChatUnlicensedPromptsCount,
        CopilotChatUnlicensedPromptsCountInEdge,
        CopilotChatUnlicensedPromptsCountInM365Copilot,
        CopilotChatUnlicensedPromptsCountInTeams,
        CopilotChatUnlicensedPromptsCountInOutlook,
        CopilotChatUnlicensedPromptsCountInCCM,
        MeetingsSummarizedCountRL7,
        MeetingMinutesSummarizedCountRL7,
        TeamsThreadsSummarizedCountRL7,
        OutlookCopilotM365ChatPromptsCountRL7,
        TeamsIntelligentRecapActionCountRL7,
        WordVisualizeAsTableActionCountRL7,
        WordChatActionCountRL7,
        PowerPointAddContentActionCountRL7,
        PowerPointOrganizePresentationActionCountRL7,
        PowerPointChatActionCountRL7,
        ExcelChatActionCountRL7,
        AllAppsCopilotActionCountRL7,
        MeetingMinutesSummarizedOrRecappedWithCopilotRL7,
        MeetingsSummarizedOrRecappedWithCopilotRL7,
        MeetingMinutesRecappedWithCopilotRL7,
        MeetingsRecappedWithCopilotRL7,
        IsReturningUserInCopilotChatUnlicensedRL7,
        IsActiveInTeamsRL28,
        IsActiveInWordRL28,
        IsActiveInPowerPointRL28,
        IsActiveInExcelRL28,
        IsActiveInOutlookRL28, //
        IsActiveInOneNoteRL28,
        IsActiveInLoopRL28,
        IsActiveInM365ChatRL28,
        IsActiveInM365CopilotRL28,
        IsEnabledInM365CopilotRL28,
        IsActiveInBusinessChatWebRL28,
        IsActiveInCopilotWithEDPInWordRL28,
        IsActiveInCopilotWithEDPInExcelRL28,
        IsActiveInCopilotWithEDPInPowerPointRL28,
        SummarizeTeamsMeetingEventsCountRL28,
        SummarizeTeamsChatEventsCountRL28,
        SummarizeEmailThreadEventsCountRL28,
        SummarizeDocumentEventsCountRL28,
        SummarizePresentationEventsCountRL28,
        GenerateEmailDraftEventsCountRL28,  //emails
        DraftDocumentEventsCountRL28,
        ModifyDocumentEventsCountRL28,
        CreatePresentationEventsCountRL28,
        MeetingsSummarizedCountRL28,
        MeetingMinutesSummarizedCountRL28,
        TeamsThreadsSummarizedCountRL28,
        TeamsComposeActionCountRL28,
        EmailCoachingActionCountRL28,
        EmailsSentWithCopilotDraftCountRL28, //emails
        M365ChatPromptsSubmittedCountRL28,
        ExcelAnalyzeActionCountRL28,
        ExcelCalculateColumnsActionCountRL28,
        ExcelCommandActionCountRL28,
        TeamsCopilotM365ChatPromptsCountRL28,
        OutlookCopilotM365ChatPromptsCountRL28,
        WordCopilotM365ChatPromptsCountRL28,
        ExcelCopilotM365ChatPromptsCountRL28,
        PowerPointCopilotM365ChatPromptsCountRL28,
        TeamsIntelligentRecapActionCountRL28,
        WordVisualizeAsTableActionCountRL28,
        WordChatActionCountRL28,
        PowerPointAddContentActionCountRL28,
        PowerPointOrganizePresentationActionCountRL28,
        PowerPointChatActionCountRL28,
        ExcelChatActionCountRL28,
        AllAppsCopilotActionCountRL28,
        AllAppsCopilotActiveWeeksRL28,
        BusinessChatWebPromptsCountRL28,
        BusinessChatWebInWordPromptsCountRL28,
        BusinessChatWebInExcelPromptsCountRL28,
        BusinessChatWebInPowerPointPromptsCountRL28,
        MeetingMinutesSummarizedOrRecappedWithCopilotRL28,
        MeetingsSummarizedOrRecappedWithCopilotRL28,
        MeetingMinutesRecappedWithCopilotRL28,
        MeetingsRecappedWithCopilotRL28,
        IsReturningUserInCopilotChatUnlicensedRL28,
        CopilotChatUnlicensedPromptsCountRL28,
        CopilotChatUnlicensedPromptsCountInEdgeRL28,
        CopilotChatUnlicensedPromptsCountInM365CopilotRL28,
        CopilotChatUnlicensedPromptsCountInTeamsRL28,
        CopilotChatUnlicensedPromptsCountInOutlookRL28,
        CopilotChatUnlicensedPromptsCountInCCMRL28,
        CopilotChatUnlicensedPromptsCountInExcelRL28
    FROM cube 
    WHERE OMSTenantId == "cc138ffb-9c4d-433b-b211-d4549ae62e8b";

//output_items =
//    SELECT
//     *
//    FROM raw
//    WHERE OMSTenantId == "cc138ffb-9c4d-433b-b211-d4549ae62e8b";

// output the result
//OUTPUT output_items
//TO SSTREAM @oStream
//WITH STREAMEXPIRY @sExpiry;

OUTPUT raw
TO  @oStreamt
USING DefaultTextOutputter(delimiter: '\t', outputHeader: true);

OUTPUT raw
TO  @oStreamp
USING Outputters.Parquet();